# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'stockApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for stockApp
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'
  pod "SwiftSpinner"

  target 'stockAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'stockAppUITests' do
    # Pods for testing
  end

end
