# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Final' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Final
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'
  pod "SwiftSpinner"
  pod "PromiseKit", "~> 6.8"

  target 'FinalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FinalUITests' do
    # Pods for testing
  end

end
